### ISSUE TITLE
failing at fobj_to_pystring

### ISSUE THREAD

**Issue by ishandutta2007** [gtzampanakis/harreplay#1]
` python harreplay.py -i ~/Desktop/charles/charlesgooglesearch.har -o charlesgooglesearch.py`
> Traceback (most recent call last):
>   File "harreplay.py", line 95, in <module>
>     main()
>   File "harreplay.py", line 92, in main
>     args.outfile.write(fobj_to_pystring(args.infile))
> TypeError: a bytes-like object is required, not 'str'

**Comment by gtzampanakis** [comment]
You are using Python 3 but this code has only been tested with Python 2.

**Comment by ishandutta2007** [comment]
Thanks, please make that explicit in readme, I see no mention of supported versions.

**Comment by gtzampanakis** [comment]
Done.

**Comment by aGrimRepoMan** [comment]
@ishandutta2007 :  Sorry for reviving an old thread, but if you needed this to work with Python 3, you could change  fobj_to_pystring() to return
`return result.encode('utf-8')`
instead of current:
`return result`

I haven't checked exhaustively, but for the one HAR file I tried when using Python 3, the above was all I had to change.
